In [2]:
import numpy as np 

In [8]:
lst=[1,2,3,4]
print(np.array(lst))
arr=np.array(lst)

[1 2 3 4]


In [6]:
type(arr)


numpy.ndarray

In [10]:
arr.shape

(4,)

In [13]:
#size of all list must be same
lst1=[1,2,3,4]
lst2=[2,3,4,5]
lst3=[6,2,4,3]

print(np.array([lst1, lst2, lst3]))
arr1=np.array([lst1,lst2,lst3])

[[1 2 3 4]
 [2 3 4 5]
 [6 2 4 3]]


In [14]:
arr1.shape

(3, 4)

In [15]:
#indexing
arr[3]

4

In [16]:
arr[3]=0
arr

array([1, 2, 3, 0])

In [17]:
arr[1:4]

array([2, 3, 0])

In [18]:
#for last element
arr[-1]

0

In [19]:
#all elements except last
arr[:-1]

array([1, 2, 3])

In [20]:
#revesring
arr[::-1]

array([0, 3, 2, 1])

In [21]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 2, 4, 3]])

In [22]:
arr1[:,1]

array([2, 3, 2])

In [23]:
arr1[1:,1:3]

array([[3, 4],
       [2, 4]])

In [24]:
arr1[1:,1:3]

array([[3, 4],
       [2, 4]])

In [27]:
arr1[:,2:]

array([[3, 4],
       [4, 5],
       [4, 3]])

In [28]:
arr1[:,2:].shape

(3, 2)

In [29]:
##EDA

In [30]:
arr


array([1, 2, 3, 0])

In [31]:
arr[arr<2]

array([1, 0])

In [33]:
#number of elemnts must be same in previous array
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 6],
       [2, 4, 3]])

In [35]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [36]:
arr*arr


array([1, 4, 9, 0])

In [37]:
arr*4

array([ 4,  8, 12,  0])

In [38]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
#to get random value
np.random.randint(10,50)

28

In [42]:
#to get more than one randome values
np.random.randint(10,50,4)

array([16, 28, 33, 16])